### PR TITLE
Added Archetype Parser

### PR DESCRIPTION
**Pull request by jaandrews**
I ended up abusing the IsParserFor method in order to get archetypes config data, as I needed the datatype id to get the archetype configuration data. Note that this was built on v 1.18.0 of archetype, so it may break for older versions.

### CODE REVIEW

**Comment by dawoe** [comment]
Hi @jaandrews 

I pullled it locally and will do some tests...If all good I will merge it in.

Thx already..

**Comment by dawoe** [comment]
Hi Andrew,

I merged this in. So it is available in the latest beta package ? Could you test that one ?

Dave

**Comment by jaandrews** [comment]
Sounds good. I'll test it by early next week. I have a few other projects on my plate right now that I need to focus on over the next couple of days.

**Comment by dawoe** [comment]
Cool... I can already confirm that it works. We have tested it on a project we recently inherited that makes heavy use of archetype.

**Pull request merged**
