### PR TITLE
Added LeBlenderGriddEditorParser

### PR DESCRIPTION
**Pull request by mistyn8**
I've dropped any logging that I had.
I wasn't sure how to register it as couldn't find an applicationStarting method?

### CODE REVIEW

**Comment by dawoe** [comment]
Hi Mike

Thx for the PR. Will try to review it somewhere this week. Want to add unit tests for it as well. Or if you can do that would be even better

Dave

**Comment by mistyn8** [comment]
added the unit test, though as per the comment not done unit testing before, so unsure how to mock content/media with udi?

**Comment by dawoe** [comment]
Hi Mike,

Can you allow me to push changes to your fork ?

https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

Dave

**Comment by mistyn8** [comment]
Hi Dave, as far as I can tell that setting is already enabled
"allow edits from maintainers" is checked
image

**Comment by dawoe** [comment]
No problem...will make the changes and merge manually

Dave

**Pull request merged**
